### ISSUE TITLE
cocoapodsへメディエーション用のライブラリ追加依頼

### ISSUE THREAD

**Issue by mogmet** [fan-ADN/nendSDK-iOS#1]
お世話になっております。

この度はcocoapodsにてメディエーションのライブラリを追加して頂きたくご連絡させていただきました。

https://github.com/CocoaPods/Specs/blob/master/Specs/NendSDK_iOS/2.5.8/NendSDK_iOS.podspec.json
上記のpodspecに以下のようにメディエーション用のライブラリも追加して頂けないでしょうか。

```
  s.vendored_libraries = "NendAd/libNendAd.a", "AdMobMediationAdapter/libAdapterNend.a"
```

また、2.5.8ではディレクトリが変わっているため、source_filesのディレクトリ位置もご確認頂けると幸いです。

何卒ご検討頂けると非常に助かります。
よろしくお願いします。

**Comment by fan-t-fukuoka** [comment]
mogmet様

お世話になっております。
株式会社ファンコミュニケーションズの福岡と申します。
この度は、cocoapodsへのライブラリ追加の件でご連絡を頂き、誠にありがとうございます。

正式にcocoapodsにてメディエーションアダプタの利用とご指摘頂いたNendSDK 2.5.8のディレクトリの件も対応いたしました。
導入手順については、こちらの[wiki](https://github.com/fan-ADN/nendSDK-admob-mediation/wiki/iOS#section2)をご確認ください。

今回のpodspecの更新に伴い、podspec内でのバージョン定義が  
NendSDK_iOSでは2.5.8.3  
NendSDK_iOS_MediationAdapterでは1.2.1.1  
となっておりますが、それぞれ中身はNendSDK_iOS-2.5.8、libAdapterNend.aのver1.2.1と同じ内容でございます。

今後とも、何卒宜しくお願い致します。

**Comment by mogmet** [comment]
福岡様

ご対応ありがとうございます！
新しいcocoapods版でも無事表示することが出来ました。

今後とも宜しくお願いします。
