### ISSUE TITLE
是什么平台

### ISSUE THREAD

**Issue by ZClee128** [fan-ADN/nendSDK-iOS#10]
要去哪里申请key，有网站吗

**Comment by fan-c-yu** [comment]
@ZClee128 
您好，感谢您的支持。

这是nend移动广告平台。
这里有中文的nend概要资料 https://board.nend.net/dl-mediapartner/
这是公司的网站 https://www.fancs.com/en
这是nend iOS SDK的使用方法 https://github.com/fan-ADN/nendSDK-iOS/wiki/nendSDK-iOS-设置指南

> 要去哪里申请key

key是通过管理界面申请的，目前管理界面只有日文版。
您可以通过下面联系我们的营业人员，他们会给您提供详细的支持。
https://www.nend.net/en/req_advertisers/form

希望对您有所帮助。
