### ISSUE TITLE
CocoaPodsでインストールするとエラー

### ISSUE THREAD

**Issue by jonnyijapan** [fan-ADN/nendSDK-iOS#2]
以下のエラーが発生します：

> Undefined symbols for architecture arm64:
>   "_OBJC_CLASS_$_NADView", referenced from:

Xcode 7.2.1

**Comment by jonnyijapan** [comment]
Pods/.../libNendAd.aをターゲットに手動で追加したら解決しました。

**Comment by fan-t-fukuoka** [comment]
jonnyijapan様

ご連絡頂きましてありがとうございます。
株式会社ファンコミュニケーションズの福岡と申します。

CocoaPodsでインストールするとエラーが発生するという件で、
こちらの下記環境ではCocoaPodsでインストールを行っても同様のエラーは確認できませんでした。
- Xcode7.2.1
- NendSDK_iOS-3.0.3
- CocoaPods 0.39.0
- Objective-CとSwiftの新規プロジェクト
- https://github.com/fan-ADN/nendSDK-iOS
  サンプルプロジェクト

> Pods/.../libNendAd.aをターゲットに手動で追加したら解決しました。

通常はCocoaPodsでインストールが成功すればlibNendAd.aを手動で追加して頂く必要はございませんので、今回のエラー原因については現状の情報では不明な状況でございます。

この度は既に解決されたとのことですが、今後もnendSDKのご利用で同じようにエラーや問題点などがございましたら、ご連絡頂ければと思います。
その際は、nendSDKバージョンや開発言語、実装内容なども可能な限り詳しい情報をご提供頂けますと幸いです。

今後ともnendをよろしくお願い致します。

**Comment by KaoriSHIGE** [comment]
福岡様

　お世話になります

　下記メール、間違って届いているようです
　needさまにはいつもお世話になっておりますが
　私はjonnyijapanではありません

　取り急ぎお知らせのみで失礼致します

# 

Kaori SHIGE
                          BlueRoy Inc.

https://www.facebook.com/BlueRoyInc
blueroyjp@gmail.com

**Comment by koogawa** [comment]
@KaoriSHIGE  さん
間違って届いたわけではなく、このリポジトリをWatchしている人全員に届いているのではないでしょうか？このメールも届いてませんか？メールを受け取りたくない場合はWatchから外せば良いと思います。
