### ISSUE TITLE
インフィード広告のIntervalの変更の仕方。

### ISSUE THREAD

**Issue by hyesang** [fan-ADN/nendSDK-iOS#4]
お世話になります。
NADNativeTableViewPlacementを見ると、ADD系しかメソードが用意されていません。
しかし、場合によってIntervalを変更したい時はどうセットすべきでしょうか？

**Comment by ghost** [comment]
@hyesang 様

お世話になっております。
株式会社ファンコミュニケーションズの真鍋と申します。

`NADNativeTableViewHelper`を使用した場合、Intervalを途中で変更することはできません。

`UITableView`上で広告表示位置を状況に応じて変更させたい場合は、`NADNativeTableViewHelper`ではなく`NADNativeClient`をお使いいただき、`loadWithCompletionBlock:`で取得した広告を任意の位置の`UITableViewCell`に表示させることで、広告表示位置をアプリ側で自由にコントロールすることが出来ます。

ご要望いただきました機能については、今後の開発の参考にさせていただきます。
今後ともnendを宜しくお願い致します。

**Comment by hyesang** [comment]
ご回答ありがとうございます。
