### ISSUE TITLE
About NADNativeTableViewPlacement

### ISSUE THREAD

**Issue by havudk1707** [fan-ADN/nendSDK-iOS#5]
Hi development team.
I have a question about NADNativeTableViewPlacement.
It's a very good function, but I have a problem.
When I use func "addRepeatInterval". 
Ex: placer.addRepeatInterval(10, inSection: 0)
How can I set the start of first ads?
Ex: I want to show ads in index: 5, 15, 25, 35 ....
Thanks for reading.

**Comment by ghost** [comment]
@havudk1707 

Thank you for your inquiry.

> Ex: I want to show ads in index: 5, 15, 25, 35 ....

You can be implemented with the following code.

``` swift
placer.addFixedIndexPath(NSIndexPath(forRow: 5, inSection: 0))
placer.addRepeatInterval(10, inSection: 0)
```

Best regards,

**Comment by havudk1707** [comment]
Wow.
I got it....
Thank you very much.
