### ISSUE TITLE
[Question] RewardVideo: No Content Error

### ISSUE THREAD

**Issue by hungtdkaopiz** [fan-ADN/nendSDK-iOS#9]
I tried to load a reward video ad but it returned error:
`nadRewardVideoAd(_:didFailToLoadWithError:) error: Error Domain=net.nend.ios.video.ad Code=204 "no content" UserInfo={NSLocalizedDescription=no content}
`
Please, help me what is this?

**Comment by fan-c-yu** [comment]
@hungtdkaopiz 
Thank you for contacting us.

> Code=204

This means there is no delivery ads.
https://github.com/fan-ADN/nendSDK-iOS/wiki/Implementation-for-Rewarded-Video-ads#loading-of-ad-is-failed

Please check these first.
- Is the language setting of the terminal and simulator set to Japanese?
- Is the device connected from Japan or is the IP address in Japan using a VPN?

Best regards.

**Comment by hungtdkaopiz** [comment]
Thank for your response 🙏. 
I set language to Japanese but I'm connecting from Viet Nam without VPN. My banner ads work well but reward video doesn't show up.
I tried to use rewarded video key in your sample project and it also work. Do I have to connect from Japan?
Thank you in advance

**Comment by fan-c-yu** [comment]
@hungtdkaopiz 
Thank you for contacting us.

Rewarded video can only be delivered to Japanese IP addresses.
We recommend using a VPN to connect.

Best regards.

**Comment by hungtdkaopiz** [comment]
I got It. Thank you so much 🙇‍♂️and have a nice day
